### ISSUE TITLE
Training stuck at epoch 1/20

### ISSUE THREAD

**Issue by jiteshm17** [you359/Keras-FasterRCNN#12]
I am using the Inception Resnet backbone and it's been almost 3 hrs and the training is still stuck at the first epoch without any progress. Can anyone please advise? I am training on my own dataset

**Comment by MaxPower2310** [comment]
I have the same problem. I tested both backbones (vgg and resnet50) and different data sets. I use Python 3.6,windows 7, Tensorflow 1.12 and keras 2.2.4 (with tensorflow backend)

**Comment by zhangyufei1995** [comment]
i have the same question, do you solve it?

**Comment by zhangyufei1995** [comment]
I am using the vgg16 backbone and it's been almost 6 hrs and the training is still stuck at the first epoch without any progress. do you solve it? I am training on my own dataset

**Comment by f4br1** [comment]
If you are using the simple parser you need to change the following line on the file "train_frcnn.py":

`train_imgs = [s for s in all_imgs if s['imageset'] == 'train']`
to
`train_imgs = [s for s in all_imgs if s['imageset'] == 'trainval']`

the issue is that the simple parser "simple_parser.py" creates a dictionary with a different key name.

**Comment by zhangyufei1995** [comment]
@f4br1  ye i have solved the problem. but how to uese the measure_map.py?

**Comment by mikechen66** [comment]
> train_imgs = [s for s in all_imgs if s['imageset'] == 'train']

What is the meaning of the above expression? What is the meaning of s?

**Comment by mikechen66** [comment]
> If you are using the simple parser you need to change the following line on the file "train_frcnn.py":
> 
> `train_imgs = [s for s in all_imgs if s['imageset'] == 'train']`
> to
> `train_imgs = [s for s in all_imgs if s['imageset'] == 'trainval']`
> 
> the issue is that the simple parser "simple_parser.py" creates a dictionary with a different key name.

I know that the above  lines of code designates train set and trainval set. However, what is the exact meaning of the  expressions(list comprehension)?  What is the meaning of s?  

kbardool completely deletes the expression from the line 109 to the line 110 in the following weblik.

https://github.com/kbardool/keras-frcnn/blob/master/train_frcnn.py
