### ISSUE TITLE
TypeError: add_weight() got multiple values for argument 'name'

### ISSUE THREAD

**Issue by hova88** [you359/Keras-FasterRCNN#13]

**Comment by collinarnett** [comment]
Could you please elaborate on the issue? Please attach a screenshot of your error.

**Comment by jmaierborst** [comment]
Did anyone fix the problem yet?

**Comment by NaehaSharif** [comment]
![image](https://user-images.githubusercontent.com/47408307/66893451-b0f55a80-f020-11e9-84f7-645eadae320d.png)

**Comment by NaehaSharif** [comment]
![image](https://user-images.githubusercontent.com/47408307/66893486-c4a0c100-f020-11e9-85c7-eaa9edb6114a.png)

**Comment by huynhcuong98** [comment]
> ![image](https://user-images.githubusercontent.com/47408307/66893486-c4a0c100-f020-11e9-85c7-eaa9edb6114a.png)
> 
> This issue is related to the class "FixedBatchNormalization"
> 
> ![image](https://user-images.githubusercontent.com/47408307/66893567-f7e35000-f020-11e9-9ca2-ae5d6b10d164.png)

i have the same problem. Can you fix this?

**Comment by KavinkumarRM** [comment]
its because the first variable inside the function 'shape' is getting assigned to the attribute name . So add shape=shape to overcome the problem.

**Comment by LEE-SEON-WOO** [comment]
> its because the first variable inside the function 'shape' is getting assigned to the attribute name . So add shape=shape to overcome the problem.
![image](https://user-images.githubusercontent.com/12380660/67959246-c337e100-fc3b-11e9-81b6-dbed846804c5.png)

**Comment by gokulprasadthekkel** [comment]
> Did anyone fix the problem yet?



> > ![image](https://user-images.githubusercontent.com/47408307/66893486-c4a0c100-f020-11e9-85c7-eaa9edb6114a.png)
> > This issue is related to the class "FixedBatchNormalization"
> > ![image](https://user-images.githubusercontent.com/47408307/66893567-f7e35000-f020-11e9-9ca2-ae5d6b10d164.png)
> 
> i have the same problem. Can you fix this?

In the add_weights() method, specify size=size, this resolved the issue for me

**Comment by saxenarohit** [comment]
Can you put the solution here? I tried a similar thing in my code (a different custom layer) and it still gives me the same error.

**Comment by gokulprasadthekkel** [comment]
You are trying to pass shape as first positional argument, but in the method definition name is the first argument. Again in the keyword arguments you are specifying name. Thats why you get a conflict.

Use something like:
        self.kernel = self.add_weight(name='kernel', 
                                      shape=(input_shape[1], self.output_dim),
                                      initializer='uniform',
                                      trainable=True)

**Comment by gokulprasadthekkel** [comment]
> Can you put the solution here? I tried a similar thing in my code (a different custom layer) and it still gives me the same error.

You are trying to pass shape as first positional argument, but in the method definition name is the first argument. Again in the keyword arguments you are specifying name. Thats why you get a conflict.

Use something like:
self.kernel = self.add_weight(name='kernel',
shape=(input_shape[1], self.output_dim),
initializer='uniform',
trainable=True)

**Comment by djpecot** [comment]
> > its because the first variable inside the function 'shape' is getting assigned to the attribute name . So add shape=shape to overcome the problem.
> 
> ![image](https://user-images.githubusercontent.com/12380660/67959291-d3e85700-fc3b-11e9-9e6d-322ffa99e48f.png)
> 
> ValueError: Attempt to convert a value (None) with an unsupported type (<class 'NoneType'>) to a Tensor
> 
> Have any solution?

I tried setting shape = shape as well, but no luck :(


`class FixedBatchNormalization(Layer):

    def __init__(self, epsilon=1e-3, axis=-1,
                 weights=None, beta_init='zero', gamma_init='one',
                 gamma_regularizer=None, beta_regularizer=None, **kwargs):

        self.supports_masking = True
        self.beta_init = initializers.get(beta_init)
        self.gamma_init = initializers.get(gamma_init)
        self.epsilon = epsilon
        self.axis = axis
        self.gamma_regularizer = regularizers.get(gamma_regularizer)
        self.beta_regularizer = regularizers.get(beta_regularizer)
        self.initial_weights = weights
        super(FixedBatchNormalization, self).__init__(**kwargs)

    def build(self, input_shape):
        self.input_spec = [InputSpec(shape=input_shape)]
        shape = (input_shape[self.axis],)

        self.gamma = self.add_weight(shape = shape,
                                     initializer=self.gamma_init,
                                     regularizer=self.gamma_regularizer,
                                     name='{}_gamma'.format(self.name),
                                     trainable=False)
        self.beta = self.add_weight(shape = shape,
                                    initializer=self.beta_init,
                                    regularizer=self.beta_regularizer,
                                    name='{}_beta'.format(self.name),
                                    trainable=False)
        self.running_mean = self.add_weight(shape = shape, initializer='zero',
                                            name='{}_running_mean'.format(self.name),
                                            trainable=False)
        self.running_std = self.add_weight(shape = shape, initializer='one',
                                           name='{}_running_std'.format(self.name),
                                           trainable=False)
`

..... down to the error message:
`in convert_to_eager_tensor
    return ops.EagerTensor(value, ctx.device_name, dtype)
ValueError: Attempt to convert a value (None) with an unsupported type (<class 'NoneType'>) to a Tensor.`

**Comment by hi0001234d** [comment]
> > Did anyone fix the problem yet?
> 
> > > ![image](https://user-images.githubusercontent.com/47408307/66893486-c4a0c100-f020-11e9-85c7-eaa9edb6114a.png)
> > > This issue is related to the class "FixedBatchNormalization"
> > > ![image](https://user-images.githubusercontent.com/47408307/66893567-f7e35000-f020-11e9-9ca2-ae5d6b10d164.png)
> > 
> > 
> > i have the same problem. Can you fix this?
> 
> In the add_weights() method, specify shape=shape, this resolved the issue for me

fixed my prob, in case of shape is passed as the first arg just name the arg like shape=(x, y)

**Comment by zrajabi** [comment]
> > Can you put the solution here? I tried a similar thing in my code (a different custom layer) and it still gives me the same error.
> 
> You are trying to pass shape as first positional argument, but in the method definition name is the first argument. Again in the keyword arguments you are specifying name. Thats why you get a conflict.
> 
> Use something like:
> self.kernel = self.add_weight(name='kernel',
> shape=(input_shape[1], self.output_dim),
> initializer='uniform',
> trainable=True)

This fixed my problem, thanks @gokulprasadthekkel

**Comment by inskaf** [comment]
@zrajabi can u show me how u fix it ?

**Comment by hardik22317** [comment]
@djpecot @LEE-SEON-WOO Have you got the answer for the error you mentioned?
ValueError: Attempt to convert a value (None) with an unsupported type (<class 'NoneType'>) to a Tensor.
I am also getting the same error in FixedBatchNormalization. Please help me solve this error. Thank you.

**Comment by djpecot** [comment]
@hardik22317 Nope sorry. I ended up ditching this tool and using Detectron instead.

**Comment by mikechen66** [comment]
It does not work. The below-mentioned solution is too vague to be understood. If you put "name" before "shape", it can not change the error. An error is an error. So the position of "shape" is the least important. Also shape=shape is a trivial trick. It can not change the error. 

> > Can you put the solution here? I tried a similar thing in my code (a different custom layer) and it still gives me the same error.
> You are trying to pass shape as first positional argument, but in the method definition name is the first argument. Again in the keyword arguments you are specifying name. Thats why you get a conflict.
> 
> Use something like:
> self.kernel = self.add_weight(name='kernel',
> shape=(input_shape[1], self.output_dim),
> initializer='uniform',
> trainable=True)

**Comment by Rakesh-MS-91** [comment]
> This is an unsolved issue. 

> i am using  tensorflow 2.3.0 and keras 2.4.3, the issue will occur. 

> couldn't` find any solution for this problem.  Nobody is addressing the issue. 

`def build(self, input_shape):
    self.input_spec = [InputSpec(shape=input_shape)]
    shape = `(input_shape[self.axis],)`

    self.gamma = self.add_weight(shape = shape,
                                 initializer=self.gamma_init,
                                 regularizer=self.gamma_regularizer,
                                 name='{}_gamma'.format(self.name),
                                 trainable=False)
    self.beta = self.add_weight(shape = shape,
                                initializer=self.beta_init,
                                regularizer=self.beta_regularizer,
                                name='{}_beta'.format(self.name),
                                trainable=False)
    self.running_mean = self.add_weight(shape = shape, initializer='zero',
                                        name='{}_running_mean'.format(self.name),
                                        trainable=False)
    self.running_std = self.add_weight(shape = shape, initializer='one',
                                       name='{}_running_std'.format(self.name),
                                       trainable=False)
`

> This code will work well if you Downgrade the version to tensorflow==1.13.1 and keras==2.1.6

> Kindly give a solution to run the same on tensorflow 2.3.0 and keras 2.4.3

**Comment by HafidzDaffa** [comment]
this code work well for me, i use tensorflow 2.0.0 with keras 2.3.0 and dont forget to add
shape = shape
