### ISSUE TITLE
ValueError: Dimension 2 in both shapes must be equal, but are 1024 and 1088. Shapes are [1,1,1024,256] and [1,1,1088,256]. for 'Assign_690' (op: 'Assign') with input shapes: [1,1,1024,256], [1,1,1088,256]

### ISSUE THREAD

**Issue by wangames** [you359/Keras-FasterRCNN#8]
When I train and test on resnet50 model, it works well. 
And when I train on inception_resnet_v2 model, it works well.
But when I test on  inception_resnet_v2 model, it raise an error: ValueError: Dimension 2 in both shapes must be equal, but are 1024 and 1088. Shapes are [1,1,1024,256] and [1,1,1088,256]. for 'Assign_690' (op: 'Assign') with input shapes: [1,1,1024,256], [1,1,1088,256].

**Comment by wangames** [comment]
when I change : 
elif C.network == 'inception_resnet_v2':
    num_features = 1024
to:
elif C.network == 'inception_resnet_v2':
    num_features = 1088
then it works.

**Comment by cenchaojun** [comment]
the same question to me .i change num_features =1088,
and it does work, thank you very much.
but the model can detect something

**Comment by collinarnett** [comment]
@wangames How did you manage to solve this problem? I am having the same issue.
